import { NextPage } from "next"
import Head from "next/head"

const Index: NextPage = () => {
    return (
        <>
            <Head>
                <title>Berangda Next JS</title>
                <meta name="description" content="Generated by Create Next Stack." />
            </Head>
            <h1>Next JS Sample Main Page</h1>
        </>
    )
}

export default Index